spring:
  application:
    name: Smart Email Application
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: smart_email_db

server:
  port: ${PORT:8080}
  servlet:
    context-path: /email-app